### ISSUE TITLE
FE: establish Dashboard

### ISSUE THREAD

**Issue by jasole1983** [jasole1983/DwayneScape#12]
### TASKS:
 - [x] Establish "logged in" redirect route 
 - [x] Create the Dashboard Component 
 - [x] Default load to user created decks
 - [x] Launch Modal trigger
 - [x] Display elements relative to User
 - [x] Styling and decorating Dashboard
