### ISSUE TITLE
FE: Pre-reqs for first MVP feature

### ISSUE THREAD

**Issue by jasole1983** [jasole1983/DwayneScape#13]
### TASKS
 - [x] Create and style Nav-Bar
 - [x] Create and style Login Modal
 - [x] Create and style Signup Modal
 - [x] Create and style Landing Page
