### ISSUE TITLE
BE: Users model creation

### ISSUE THREAD

**Issue by jasole1983** [jasole1983/DwayneScape#14]
### TASKS
 - [x] Setup Users Model 
 - [x] Setup Users Migrations
 - [x] Setup Users seed data
