### ISSUE TITLE
BE: Decks model creation

### ISSUE THREAD

**Issue by jasole1983** [jasole1983/DwayneScape#15]
### TASKS
 - [x] Setup Decks Model
 - [x] Setup Decks Migrations
 - [x] Setup Decks seed data
