### ISSUE TITLE
BE: Cards Model creation

### ISSUE THREAD

**Issue by jasole1983** [jasole1983/DwayneScape#16]
### TASKS
 - [x] Setup Cards Model
 - [x] Setup Cards Migrations
 - [x] Setup Cards seed data
