### ISSUE TITLE
Study Page Component - Question

### ISSUE THREAD

**Issue by jasole1983** [jasole1983/DwayneScape#21]
> Display the question full and bright, partial fade for rest of phases in the cycle
### TASKS
 - [ ] Create element to display current question
 - [ ] Style element and transform opaqueness for subsequent phases
 - [ ] Create whatever elements above question as well
