### ISSUE TITLE
Study Page Component - Rating

### ISSUE THREAD

**Issue by jasole1983** [jasole1983/DwayneScape#23]
> Should display 5 levels of rating regarding mastery of card, but only be enabled during its phase
### TASKS
 - [ ] Create 5 elements, each with their own color
 - [ ] Able to be clicked after answer phase
 - [ ] Each should change state to adjust meter
