### ISSUE TITLE
Study Session Complete Modal

### ISSUE THREAD

**Issue by jasole1983** [jasole1983/DwayneScape#24]
> After meter is filled display Success modal with stats
### TASKS
 - [ ] Create the Success Page popup
 - [ ] Display overall stats for study session
 - [ ] Option to repeat same study Session
